#!/bin/bash

set -e -o pipefail

if [[ $1 == 'careless-delivery' || $1 == 'cd' ]]; then
    if [[ $2 == '--help' ]]; then
        echo 'NAME:
   careless-delivery - create a careless continous deployment experience for an already pushed app

USAGE:
   cf careless-delivery APP_NAME 

ALIAS:
   cd

OPTIONS:

ENVIRONMENT:
   CF_USERNAME        Username for the pipeline to access the app deployed to Cloud Foundry 
   CF_PASSWORD        Password for the pipeline to access the app deployed to Cloud Foundry 

SEE ALSO:
   push'
        exit 0
    fi

    GIT_URL=$(git remote -v | awk '{print $2}' | head -n 1)
    APP_NAME="$2"
    CF_API=$(cf t | grep "^api endpoint:" | awk '{print $3}')
    CF_ORG=$(cf t | grep "^org:" | awk '{print $2}')
    CF_SPACE=$(cf t | grep "^space:" | awk '{print $2}')

    if [[ ! -d .cd ]] then
        mkdir .cd
    fi

    BUILDPACK=$(cf a "${APP_NAME}" | grep "^buildpack:" | awk '{print $2}')

    BUILDPACK_PIPELINE="${BUILDPACK}-pipeline.yml"

    PIPELINE=".cf/${BUILDPACK_PIPELINE}"
    curl "https://raw.githubusercontent.com/evoila/cfsummitna2019/master/${BUILDPACK_PIPELINE}" -o "${PIPELINE}"

    fly -t gstack login -k -u cbrinker@evoila.de -p gst4ckr0cks
    fly -t gstack set-pipeline -n -p "${APP_NAME}" -c "${PIPELINE}" \
        -v cf_username="${CF_USERNAME}" \
        -v cf_password="${CF_PASSWORD}" \
        -v cf_api="${CF_API}" \
        -v app_name="${APP_NAME}" \
        -v git_url="${GIT_URL}" \
        -v cf_org="${CF_ORG}" \
        -v cf_space="${CF_SPACE}"
else
    cf "$1"
fi